
clone application repository:
  image: vsoare/image-to-execute-pipelines:0.0.1
  script:
    - cd /home/custom-application
    - git clone https://github.com/valentinsoare/fastwebserver.git
    - du -sh .
    - ls -latr
  artifacts:
      paths:
        - /builds/vsoare/fastwebserver_with_cicd
