stages:
  - clone
  - test_clone
#  - clone application repository
#  - build application binary image
#  - build docker image with application binary
#  - deploy the application in a docker container


clone application repository:
  stage: clone
  image: vsoare/image-to-execute-pipelines:0.0.1
  script:
    - cd /home/custom-application
    - git clone https://github.com/valentinsoare/fastwebserver.git
    - du -sh .
    - ls -latr
  artifacts:
      paths:
        - /builds/vsoare/fastwebserver_with_cicd

test if cloning ok:
  stage: test_clone
  image: vsoare/image-to-execute-pipelines:0.0.1
  script:
    - du -sh .
    - if [[ ! -e ./src || ! -d ./src ]]; then
        printf "\033[31m%s\033[0m\n" " - > src directory doesn't exist!";
        exit 1;
      fi
      
      printf "\033[32m%s\033[0m\n" " - > src directory exists!";
