stages:
  - Clone
  - Test_Clone
  - Build_Application_Binary
  - Build_Application_Image

clone application repository:
  stage: Clone
  image: vsoare/image-to-execute-pipeline:0.0.1
  script:
    - cd /home/custom-application
    - git clone https://gitlab.com/vsoare/fastwebserver_with_cicd.git
    - du -sh .
  artifacts:
      paths:
        - /builds/vsoare/fastwebserver_with_cicd

test if cloning successfully:
  stage: Test_Clone
  image: vsoare/image-to-execute-pipeline:0.0.1
  script:
    - if [[ ! -e ./src || ! -d ./src ]]; then
        printf "\033[31m%s\033[0m\n" " - > src directory doesn't exist. project was not cloned with success!";
        exit 1;
      fi
      
      printf "\033[32m%s\033[0m\n" " - > src directory exists. fastwebserver successfully cloned!";
  artifacts:
    paths:
      - /builds/vsoare/fastwebserver_with_cicd


build application binary from source code:
  stage: Build_Application_Binary
  image: vsoare/image-to-execute-pipeline:0.0.1
  script:
    - chmod +x building-binary-image.sh
    - ./building-binary-image.sh
