# Pipeline with stages and jobs

stages:
  - Clone
  - Test_Clone
  - Build_Application_Binary
  - Build_Application_Image

clone application repository:
  stage: Clone
  image: alpinelinux/alpine-gitlab-ci
  script:
    - git clone https://gitlab.com/vsoare/fastwebserver.git
  artifacts:
      paths:
        - /builds/vsoare/fastwebserver

test if cloning successfully:
  stage: Test_Clone
  image: alpine:3.19
  script:
    - if [[ ! -e ./src || ! -d ./src ]]; then
        printf "\033[31m%s\033[0m\n" " - > src directory doesn't exist. project was not cloned with success!";
        exit 1;
      fi
      
      printf "\033[32m%s\033[0m\n" " - > src directory exists. fastwebserver successfully cloned!";
  artifacts:
    paths:
      - /builds/vsoare/fastwebserver


build application binary from source code:
  stage: Build_Application_Binary
  image: vsoare/execute_pipelines_java_code:0.0.1
  script:
    - chmod +x build-binary-image.sh
    - ./build-binary-image.sh
  artifacts:
    paths:
      - /builds/vsoare/fastwebserver

build application image:
  stage: Build_Application_Image
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -f ./build-docker-image-with-application-binary-image.DockerFile -t vsoare/fastwebserver:0.0.1 .
    - echo "${DOCKER_TOKEN}" | docker login --username ${DOCKER_USERNAME} --password-stdin
    - docker push vsoare/fastwebserver:0.0.1
