# Pipeline to build a binary image and then to deploy it as a docker image

stages:
  - Clone
  - Test_Clone
  - Build_Application_Binary
  - Build_Application_Image

clone application repository:
  stage: Clone
  tags:
    - webserver
  image: alpinelinux/alpine-gitlab-ci
  script:
    - printf "\033[1;5;42m %s \033[0m \n" "Cloning the repository...."
    - git clone https://gitlab.com/vsoare/fastwebserver.git
  artifacts:
      paths:
        - /builds/vsoare/fastwebserver

test if cloning successfully:
  stage: Test_Clone
  tags:
    - webserver
  image: alpine:3.19
  script:
    - printf "\033[1;5;42m %s \033[0m \n" "Checking if repository was cloned as it should!"
    - if [[ ! -e ./src || ! -d ./src ]]; then
        printf "\033[31m%s\033[0m\n" " - > src directory doesn't exist. project was not cloned with success!";
        exit 1;
      fi
      
      printf "\033[1;5;42m %s \033[0m \n" " - > src directory exists. fastwebserver successfully cloned!";
  artifacts:
    paths:
      - /builds/vsoare/fastwebserver


build application binary from source code:
  stage: Build_Application_Binary
  tags:
    - webserver
  image: vsoare/execute_pipelines_java_code:0.0.1
  script:
    - printf "\033[1;5;42m %s \033[0m \n" "Make the script executable."
    - chmod +x build-binary-image.sh
    - printf "\033[1;5;42m %s \033[0m \n" "Execute the script that builds the binary with GraalVM."
    - ./build-binary-image.sh
  artifacts:
    paths:
      - /builds/vsoare/fastwebserver

build application image:
  stage: Build_Application_Image
  tags:
    - webserver
  image: docker:stable
  services:
    - docker:dind
  script:
    - printf "\033[1;5;42m %s \033[0m \n" "Build the docker image."
    - sudo docker build -f ./build-docker-image-with-application-binary-image.DockerFile -t vsoare/fastwebserver:0.0.1 .
    - printf "\033[1;5;42m %s \033[0m \n" "Authenticate to Docker Hub Registry."
    - echo "${DOCKER_TOKEN}" | sudo docker login --username ${DOCKER_USERNAME} --password-stdin
    - printf "\033[1;5;42m %s \033[0m \n" "Push the docker image to registry."
    - sudo docker push vsoare/fastwebserver:0.0.1
