version: '3.9'
name: "deploy-application-docker-image"

services:
  fastwebserver:
    build:
      context: .
      dockerfile: build-docker-image-with-application-binary-image.DockerFile
    image: vsoare/fastwebserver:0.0.1
    container_name: fastwebserver
    ports:
      - "8080:8080"
    networks:
      - nw_fast
    volumes:
      - application-storage:/home/fastwebserver

networks:
  nw_fast:
    external: true
    name: nw_fast

volumes:
  application-storage:
    external: true
    name: application-storage
